CREATE PROCEDURE INSERT_CATEGORIES_WITH_PRODUCTS(@Quantity INT)
AS
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION INSERT_CATEGORIES_WITH_PRODUCTS;
			PRINT 'ON COMMIT TRANSACTION';
				
				WHILE @Quantity>0 BEGIN
					
				INSERT INTO categoria_producto (nombre_categoria)
				VALUES ('CATEGORIA');

				DECLARE @CATEGORY_ID INT = SCOPE_IDENTITY()

				INSERT INTO producto(nombre_producto, id_categoria_producto)
				VALUES ('PRODUCTO', @CATEGORY_ID )



		
				DECLARE @PRODUCT_ID INT = SCOPE_IDENTITY()

				PRINT @PRODUCT_ID
				END;

		COMMIT TRANSACTION INSERT_CATEGORIES_WITH_PRODUCTS;
	END TRY  
	
	BEGIN CATCH  
		PRINT 'ON ROLLBACK TRANSACTION'+ CHAR(13) + ERROR_MESSAGE();		
		ROLLBACK TRANSACTION INSERT_CATEGORIES_WITH_PRODUCTS;
	END CATCH 
END;
GO

EXEC INSERT_CATEGORIES_WITH_PRODUCTS @Quantity=1
