CREATE PROCEDURE INSERT_CATEGORIES_WITH_PRODUCTS(@Quantity INT)
AS
	WHILE (@Quantity>=0) BEGIN
		PRINT @Quantity
		SET @Quantity-=1;
		CONTINUE
	END
GO

EXEC INSERT_CATEGORIES_WITH_PRODUCTS @Quantity = 3