CREATE PROCEDURE INSERT_CATEGORIES_WITH_PRODUCTS(@Quantity INT)
AS
	BEGIN TRY
		BEGIN TRANSACTION INSERT_CATEGORIES_WITH_PRODUCTS;
				PRINT 'ON COMMIT TRANSACTION';
				WHILE @Quantity>0
					BEGIN
						PRINT 'ON WHILE LOOP';
						SET @Quantity-=1;
					END;
				THROW 50000,'EXCEPTION THROWED',0;
		COMMIT TRANSACTION INSERT_CATEGORIES_WITH_PRODUCTS;
	END TRY  
	
	BEGIN CATCH  
		PRINT 'ON ROLLBACK TRANSACTION';
		ROLLBACK TRANSACTION INSERT_CATEGORIES_WITH_PRODUCTS;
	END CATCH 
GO

EXEC INSERT_CATEGORIES_WITH_PRODUCTS @Quantity = 3